# Generated by Django 4.2.5 on 2023-12-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='thing',
        ),
        migrations.AddField(
            model_name='images',
            name='thing',
            field=models.ManyToManyField(related_name='thing', to='one.things', verbose_name='Для'),
        ),
    ]
