# Generated by Django 4.2.5 on 2023-12-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_remove_images_thing_images_thing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='thing',
        ),
        migrations.AddField(
            model_name='images',
            name='thing',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='thing', to='one.things', verbose_name='Для'),
            preserve_default=False,
        ),
    ]
