# Generated by Django 5.0.1 on 2024-01-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_alter_purchases_created_alter_purchases_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
    ]
