# Generated by Django 4.2.5 on 2023-12-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_remove_things_img_alter_images_thing'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='img',
            field=models.ImageField(blank=True, upload_to='image/%Y', verbose_name='Изображение'),
        ),
    ]
