# Generated by Django 4.2.5 on 2023-12-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_things_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='img2',
            field=models.ImageField(blank=True, upload_to='image/%Y', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='things',
            name='img3',
            field=models.ImageField(blank=True, upload_to='image/%Y', verbose_name='Изображение'),
        ),
    ]
