# Generated by Django 5.0.1 on 2024-01-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_alter_purchases_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='things',
            name='user',
        ),
    ]
