# Generated by Django 4.2.5 on 2024-01-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_remove_category_user_remove_things_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
