# Generated by Django 4.2.5 on 2024-01-23 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('one', '0007_rename_img_things_one_img_rename_img2_things_two_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('img', models.ImageField(upload_to='image/%Y', verbose_name='Изображение')),
                ('selected_size', models.IntegerField(max_length=200, verbose_name='Выбранный размер')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
